jasypt:
   encryptor:
      password: ${jasyptpwd:secretkey}
      algorithm: PBEWithMD5AndDES

server:
   port: 9090
   servlet:
      context-path: /estacionamiento
      session:
         timeout: 21600s

spring:
   datasource:
      driver-class-name: org.postgresql.Driver
      type: com.zaxxer.hikari.HikariDataSource
      jdbcUrl: jdbc:postgresql://127.0.0.1:5432/EstacionamientoADN
      username: postgres
      password: juan.caro
      hikari:
         poolName: pool
